### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by moh1122** [Le0nLyn/ARMotionCaptureEffectTest#1]
Hello
I have iOS 13 beta 3 on iPhone XS max but when I run it its crashing on:
 _ = Entity.loadBodyTrackedAsync(named: "character/robot").sink(receiveCompletion

Asif the robot is not loading but I see the robot.usdz file under character.
Any clue?

**Comment by Le0nLyn** [comment]
I have not encountered this error yet. Which version of Xcode did you use? I was using **Xcode 11.0 beta 3**.

**Comment by moh1122** [comment]
im using Xcode 11 beta 1
ill install beta 3 and try 
thank you

**Comment by moh1122** [comment]
solved it ;)
